# Generated by Django 4.1 on 2022-09-19 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checho.clientes'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checho.empleados'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checho.servicios'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checho.administradores'),
        ),
    ]
